module DMC
  module TypeRework
    # Constant defining if you are using the rebalanced effectiveness calculation (true) or not (false)
    MAINTYPE = true


    # Constant defining the Type3 of a Pokemon by form
    # @return [Hash{ Array<Symbol, Integer> => Symbol }
    # Example: [:bulbasaur, 0] => :fire
    CREATURE_TYPE_3 = {
      [:battling, 0] => :flying,
      [:nibblet, 0] => :flying,
      [:echobat, 0] => :flying,
      [:sonarion, 0] => :flying,
      [:xenobat, 0] => :flying,
      [:overseer, 0] => :psychic,
      [:hellbat, 0] => :flying,
      [:hellwing, 0] => :fire,
      [:lamplet, 0] => :copper,
      [:amplet, 0] => :steel,
      [:luxion, 0] => :steel,
      [:wicklet, 0] => :luz,
      [:wickelabra, 0] => :luz,
      [:lunaryx, 0] => :luz,
      [:mourndelume, 0] => :dark,
      [:waxy, 0] => :luz,
      [:hivewax, 0] => :luz,
      [:meltqueen, 0] => :royal,
      [:combuxtix, 0] => :poison,
      [:primawurlm, 0] => :dragon,
      [:cragwurm, 0] => :crystal,
      [:toadrum, 0] => :music,
      [:glowtoad, 0] => :luz,
      [:toadossal, 0] => :music,
      [:sunshroom, 0] => :holy,
      [:ironmula, 0] => :steel,
      [:sanchariot, 0] => :royal,
      [:burriesta, 0] => :dream,
      [:mellumine, 0] => :luz,
      [:nebuluminous, 0] => :luz,
      [:jellyvoltious, 0] => :electric,
      [:jellumi, 0] => :sweet,
      [:jellatine, 0] => :sweet,
      [:royalatine, 0] => :royal,
      [:neurumi, 0] => :psychic,
      [:braindussa, 0] => :psychic,
      [:vilevora, 0] => :poison,
      [:tyranovine, 0] => :fire,
      [:bombusk, 0] => :explosive,
      [:jewelusk, 0] => :crystal,
      [:magnehusk, 0] => :magnetism,
      [:crochetta, 0] => :hearth,
      [:crochetress, 0] => :hearth,
      [:dreamspinner, 0] => :dream,
      [:dreamweaver, 0] => :dream,
      [:silkmourne, 0] => :dark,
      [:widomourne, 0] => :dark,
      [:wonderhops,0] => :dream,
      [:craterhop, 0] => :luz,
      [:deathelope, 0] => :dark,
      [:wolfubis, 0] => :spirit,
      [:tundragnar, 0] => :fighting,
      [:sorbowolf, 0] => :sweet,
      [:sulfurion, 0] => :electric,
      [:skelberus, 0] => :demon,
      [:vigilobox, 0] => :guardian,
      [:puffpowolf, 0] => :yarn,
      [:woofwoofer, 0] => :music,
      [:chihuahualf, 0] => :demon
      [:chocogildbun, 0] => :gold,
      [:flutterling, 0] => :luz,
      [:celestling, 0] => :luz,
      [:dryadessa, 0] => :guardian,
      [:lullamae, 0] => :dream,
      [:carolilia, 0] => :hearth,
    }
    CREATURE_TYPE_3.default = :__undef__
  end